title: ahmetcan
subtitle: Machine Learning / Mobile Application / Web Full Stack
description: Software Developer/ Machine Learning . Mobile Application . Web Application
url: "http://ahmetcan.com.tr" 
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
#    - text: Gallery
#      url: /gallery
#    - text: Styleguide
#      url: /styleguide
#    - text: Get Started
#      url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Ahmet CAN
#author_bio: Ahmet CAN BIO :D
author_email: "mail@ahmetcan.com.tr"
author_location: Turkey
author_website_url: "https://ahmetcan.com.tr"
typewrite-text: work smarter !not harder


# Experiences
author_work_experiences:
            - company_name: Turkish Insurance Company Heardquarter IT(25000+ employees)
              company_logo: company.png
              company_url: ... #https://google.com
              designation: Senior Software Developer
              description: Istanbul/Turkey 
              visibility: true
            - company_name: Turkish Bank(investment) IT(9000+ employees)
              company_logo: company.png
              company_url: ... 
              designation: Senior Software Developer
              description: Istanbul/Turkey
              visibility: true
            - company_name: Software Company(1000+ employees)
              company_logo: company.png
              company_url: ... 
              designation: Senior Mobile App Developer
              description: Istanbul/Turkey 
              visibility: true
            - company_name: Software Company in Telecommunication(1000+ employees)
              company_logo: company.png
              company_url: ... 
              designation: Senior Software Developer
              description: Istanbul/Turkey 
              visibility: true
            - company_name: Software Company in Communication(15000+ employees)
              company_logo: company.png
              company_url: ... 
              designation: Senior Software Developer
              description: Istanbul/Turkey 
              visibility: true
            - company_name: Software Company in Banking (500+ employees)
              company_logo: company.png
              company_url: ... 
              designation: Senior Software Developer 
              description: Ankara/Turkey 
              visibility: true
            - company_name: Defence Technology Company (1200+ employees)
              company_logo: company.png
              company_url: ... 
              designation: Senior Software Developer
              description: Ankara/Turkey 
              visibility: true

# Education
author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: false

# Projects
author_project_details:
              - project_thumbnail: dragoman.png
                project_title: Dragoman Chat Translator
                project_description: Android App on PlayStore
                project_url: https://play.google.com/store/apps/details?id=ahmetcan.dragoman.whatsapp
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: false

# social links
twitter_username: ahmetcancomtr
github_username:  ahmetcancomtr
facebook_username: ahmetcancomtrfb
linkedin_username: ahmetcancomtr
instagram_username: ahmetcancomtr
medium_username: ahmetcancomtr

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
jekyll-archives:
   enabled:
     - categories
   layout: archive
   permalinks:
     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
